#!/bin/bash

while getopts ":b" opt; do
    case $opt in
        b)
			ARGS_BEFORE=true
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            ;;
		:)
			echo "IDK"
			;;
    esac
done

shift "$((OPTIND - 1))"

PROGRAM=$1
FILENAME=$2
ARGS=${@:3}

unlit=`echo $FILENAME |  sed 's/\(.*\).lit/\1/'`

sed -n 's/^    //p' $FILENAME > $unlit

if $ARGS_BEFORE; then
	$PROGRAM $ARGS $unlit
else
	$PROGRAM $unlit $ARGS
fi
rm $unlit
